definitions:
  main.welcomeModel:
    properties:
      id:
        example: 1
        format: int64
        type: integer
      name:
        example: account name
        type: string
    type: object
info:
  contact: {}
paths:
  /welcome/{name}:
    get:
      consumes:
      - application/json
      description: 아 왤케 어려워
      parameters:
      - description: User name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.welcomeModel'
      summary: 테스트입니다
swagger: "2.0"
